# Generated by Django 6.0.4 on 2026-06-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('categoria_descricao', models.TextField(blank=True, max_length=255)),
                ('categoria_imagem', models.ImageField(blank=True, upload_to='fotos/categorias')),
            ],
        ),
    ]
