# Generated by Django 6.0.4 on 2026-06-10 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('produto_descricao', models.TextField(blank=True, max_length=300)),
                ('produto_preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('produto_imagens', models.ImageField(upload_to='fotos/produto')),
                ('produto_tipo', models.CharField(choices=[('VENDA', 'venda'), ('DOACAO', 'doação')], default='VENDA', max_length=10)),
                ('produto_esta_disponivel', models.BooleanField(default=True)),
                ('produto_criado_em', models.DateField(auto_now_add=True)),
                ('produto_modificado_em', models.DateField(auto_now=True)),
                ('produto_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
