# Generated by Django 6.0.4 on 2026-06-23 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_produto_preco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='doacao_confirmada_doador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='doacao_confirmada_recebedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='donatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
