# Generated by Django 6.0.4 on 2026-06-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_doacao_confirmada_doador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produto_nome',
            field=models.CharField(max_length=200),
        ),
    ]
