# Generated by Django 6.0.4 on 2026-06-16 02:08

import usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[usuario.models.validar_cpf]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, validators=[usuario.models.validar_maioridade]),
        ),
    ]
