# Generated by Django 6.0.4 on 2026-06-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_cpf_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='moradores_casa',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='renda_mensal_casa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
